config/routes.rb
Rails.application.routes.draw do
  resources :resorts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resort.rb
class Resort < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  before_action :set_resort, only: [:show, :edit, :update, :destroy]

  # GET /resorts
  # GET /resorts.json
  def index
    @resorts = Resort.all
    render json: { resorts: @resorts }, status: :ok
  end

  # GET /resorts/1
  # GET /resorts/1.json
  def show
  end

  # GET /resorts/new
  def new
    @resort = Resort.new
  end

  # GET /resorts/1/edit
  def edit
  end

  # POST /resorts
  # POST /resorts.json
  def create
    @resort = Resort.new(resort_params)

    respond_to do |format|
      if @resort.save
        format.html { redirect_to @resort, notice: 'Resort was successfully created.' }
        format.json { render :show, status: :created, location: @resort }
      else
        format.html { render :new }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resorts/1
  # PATCH/PUT /resorts/1.json
  def update
    respond_to do |format|
      if @resort.update(resort_params)
        format.html { redirect_to @resort, notice: 'Resort was successfully updated.' }
        format.json { render :show, status: :ok, location: @resort }
      else
        format.html { render :edit }
        format.json { render json: @resort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resorts/1
  # DELETE /resorts/1.json
  def destroy
    @resort.destroy
    respond_to do |format|
      format.html { redirect_to resorts_url, notice: 'Resort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resort
      @resort = Resort.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resort_params
      params.require(:resort).permit(:name, :snow_fall, :main_parking, :herm_parking, :lift_1, :lift_2, :lift_3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnoApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resorts/_form.html.erb
<%= form_with(model: resort, local: true) do |form| %>
  <% if resort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resort.errors.count, "error") %> prohibited this resort from being saved:</h2>

      <ul>
        <% resort.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :snow_fall %>
    <%= form.text_field :snow_fall %>
  </div>

  <div class="field">
    <%= form.label :main_parking %>
    <%= form.text_field :main_parking %>
  </div>

  <div class="field">
    <%= form.label :herm_parking %>
    <%= form.text_field :herm_parking %>
  </div>

  <div class="field">
    <%= form.label :lift_1 %>
    <%= form.text_field :lift_1 %>
  </div>

  <div class="field">
    <%= form.label :lift_2 %>
    <%= form.text_field :lift_2 %>
  </div>

  <div class="field">
    <%= form.label :lift_3 %>
    <%= form.text_field :lift_3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resorts/edit.html.erb
<h1>Editing Resort</h1>

<%= render 'form', resort: @resort %>

<%= link_to 'Show', @resort %> |
<%= link_to 'Back', resorts_path %>

app/views/resorts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resorts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Snow fall</th>
      <th>Main parking</th>
      <th>Herm parking</th>
      <th>Lift 1</th>
      <th>Lift 2</th>
      <th>Lift 3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resorts.each do |resort| %>
      <tr>
        <td><%= resort.name %></td>
        <td><%= resort.snow_fall %></td>
        <td><%= resort.main_parking %></td>
        <td><%= resort.herm_parking %></td>
        <td><%= resort.lift_1 %></td>
        <td><%= resort.lift_2 %></td>
        <td><%= resort.lift_3 %></td>
        <td><%= link_to 'Show', resort %></td>
        <td><%= link_to 'Edit', edit_resort_path(resort) %></td>
        <td><%= link_to 'Destroy', resort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resort', new_resort_path %>

app/views/resorts/new.html.erb
<h1>New Resort</h1>

<%= render 'form', resort: @resort %>

<%= link_to 'Back', resorts_path %>

app/views/resorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resort.name %>
</p>

<p>
  <strong>Snow fall:</strong>
  <%= @resort.snow_fall %>
</p>

<p>
  <strong>Main parking:</strong>
  <%= @resort.main_parking %>
</p>

<p>
  <strong>Herm parking:</strong>
  <%= @resort.herm_parking %>
</p>

<p>
  <strong>Lift 1:</strong>
  <%= @resort.lift_1 %>
</p>

<p>
  <strong>Lift 2:</strong>
  <%= @resort.lift_2 %>
</p>

<p>
  <strong>Lift 3:</strong>
  <%= @resort.lift_3 %>
</p>

<%= link_to 'Edit', edit_resort_path(@resort) %> |
<%= link_to 'Back', resorts_path %>